sudo: required

language: java

services:
  - docker

script:
    # - printf 'VER\t${project.version}' | mvn help:evaluate | grep '^VER' | cut -f2
  # - mvn clean install -Ddocker.useColor=false -Ddocker.showLogs -Pdocker -Pjacoco coveralls:report
  - version=$(echo '1.0')
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t crystaldust/testing:${version} ./
  - docker push crystaldust/testing:${version}

