sudo: required

language: java

services:
  - docker

script:
    # - printf 'VER\t${project.version}' | mvn help:evaluate | grep '^VER' | cut -f2
  # - mvn clean install -Ddocker.useColor=false -Ddocker.showLogs -Pdocker -Pjacoco coveralls:report
  - version=$(echo '1.0')
  - docker build -t crystaldust/testing:${version} ./
  - echo "${TRAVIS_TAG}"

after_success:
  - if [ "$TRAVIS_TAG" = "true" ]; then bash -x ./release.sh ; fi

